[OG - 29] add delete project
DgtlBureau/outReach-front pull request #6
Opened 2024-08-14 15:43 UTC by Alfat1989

2024-08-14 17:54 UTC, vladilen597 commented
![image](https://github.com/user-attachments/assets/be431a77-37e2-4b37-828c-0d5cd0525b7e)
Темная тема интересно выглядит)

2024-08-14 17:56 UTC, vladilen597 commented on src/components/HomePage/Home/ProjectList/ProjectList.tsx
> +          onCloseClick={removeProject}
Тут лишнее прокидывание пропса, достаточно будет сделать тут  onCloseClick={() => removeProject(project.id)} и не придется прокидывать id, чтобы его внутри ProjectItem использовать

2024-08-14 18:01 UTC, vladilen597 commented on src/components/HomePage/Home/ProjectList/ProjectList.tsx
> +      enqueueSnackbar('Проект удален', { variant: 'success',})
У нас всё на английском)

2024-08-14 18:01 UTC, vladilen597 commented on src/components/HomePage/Home/ProjectList/ProjectList.tsx
> +      enqueueSnackbar('Проект удален', { variant: 'success',})
У нас всё на английском)

2024-08-14 18:01 UTC, vladilen597 commented on src/components/HomePage/Home/ProjectList/ProjectList.tsx
> +          onCloseClick={removeProject}
Тут лишнее прокидывание пропса, достаточно будет сделать тут
`onCloseClick={() => removeProject(project.id)}` 
и не придется прокидывать id, чтобы его внутри ProjectItem использовать

2024-08-14 18:05 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/IcpTable/IcpBody/IcpBody.tsx
> +      <div className={inputBoxClass}>
Поменяй присвоение className под общий стиль `'inputBoxClass'` а не `{inputBoxClass}`

2024-08-14 18:43 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/IcpTable/IcpBody/IcpBody.tsx
> +      <div className={inputBoxClass}>
убери класс на котором не стилей

2024-08-14 19:03 UTC, vladilen597 commented
![image](https://github.com/user-attachments/assets/b38e14fa-9bda-46dd-84d7-1e558ab84141)
Поменяй цвет галки с зеленого на фиолетовый как везде

2024-08-14 19:04 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/IcpTable/IcpBody/IcpBody.tsx
> +    setTimeout(() => {
Зачем тут таймауты?

2024-08-14 19:10 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/ProductForm.scss
> +      .product-form__add-lead-dropdown-button,.product-form__delete-button {
По бэму лучше сделай отдельный класс, чтобы не дублировать ниже

2024-08-14 19:11 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/ProductForm.tsx
> +        if (res.data.message !== 'Success') {
Может лучше по статусу проверять?

2024-08-14 19:13 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/ProductForm.tsx
> +          refetch={()=>refetch()}
`refetch={refetch}` достаточно

2024-08-14 19:15 UTC, vladilen597 requested changes
Исправить комменты

2024-08-14 21:55 UTC, Alfat1989 commented on src/components/ProductPage/Product/ProductForm/IcpTable/IcpBody/IcpBody.tsx
> +    setTimeout(() => {
при нажатии  на "галочку" происходит смена фокуса, так как это не поле инпута не происходит событие фокуса и не происходит клик по кнопке. Для этого происходит задержка по времени.

2024-08-14 22:04 UTC, Alfat1989 commented on src/components/ProductPage/Product/ProductForm/ProductForm.tsx
> +        if (res.data.message !== 'Success') {
не приходит. Точнее приходит, но и там и там он 200 и ok, поэтому сделал такую привязку. Так бы с удовольствием))

2024-08-14 22:15 UTC, Alfat1989 commented on src/components/ProductPage/Product/ProductForm/IcpTable/IcpBody/IcpBody.tsx
> +      <div className={inputBoxClass}>
они в файле компонента

2024-08-14 22:20 UTC, vladilen597 commented on src/components/ProductPage/Product/ProductForm/IcpTable/IcpBody/IcpBody.tsx
> +      <div className={inputBoxClass}>
Да, я вроде удалял этот коммент, сори

2024-08-15 12:15 UTC, vladilen597 approved these changes

2024-08-15 13:22 UTC, merged